title: Blogging JavaScript
author:  ![sidharth74659]( https://codepen.io/sidharth74659/)
email: sidharthsid74659@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Front-end Developer. I write what i learn and always there to learn something new. Love productivity

# social links
twitter_username: Srikanth74659 # DO NOT include the @ character, or else the build will fail!
github_username:  sidharth74659 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
